### ISSUE TITLE
Blender 4.1 still incompatible

### ISSUE THREAD

**Issue by SlendyOfDaMawn** [Grimrukh/soulstruct-blender#45]
_Now Blender 4.1 compatible!_
nah lol

Loading 1.9.1 up in Blender 4.1 throws this error:

```
Traceback (most recent call last):
  File "G:\Steam\steamapps\common\Blender\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Steam\steamapps\common\Blender\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_soulstruct\__init__.py", line 26, in <module>
    importlib.reload(sys.modules[module_name])
  File "G:\Steam\steamapps\common\Blender\4.1\python\Lib\importlib\__init__.py", line 159, in reload
    raise ImportError(msg.format(parent_name),
ImportError: parent 'soulstruct_havok' not in sys.modules
```

Issue #40 appears unresolved.

**Comment by Grimrukh** [comment]
Fixed in 1.9.2 for real I believe!

**Comment by SlendyOfDaMawn** [comment]
https://github.com/Grimrukh/soulstruct-blender/assets/34933487/e4e632c7-5bdd-4db9-b27b-c2558ae88f26

**Comment by mifozski** [comment]
I still have an error installing 1.9.3 on Blender 4.1.1:
<img width="694" alt="image" src="https://github.com/Grimrukh/soulstruct-blender/assets/3611730/b3255a76-e32f-43ff-b681-3cd862055ce5">
